=== api-evangelist/conductor/json-schema/conductor-conductor-workflow-summary-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "WorkflowSummary",
  "type": "object",
  "properties": {
    "workflowId": {
      "type": "string"
    },
    "workflowType": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "correlationId": {
      "type": "string"
    },
    "startTime": {
      "type": "string"
    },
    "updateTime": {
      "type": "string"
    },
    "endTime": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "input": {
      "type": "string"
    },
    "output": {
      "type": "string"
    },
    "reasonForIncompletion": {
      "type": "string"
    },
    "executionTime": {
      "type": "integer"
    },
    "event": {
      "type": "string"
    },
    "failedReferenceTaskNames": {
      "type": "string"
    },
    "priority": {
      "type": "integer"
    }
  }
}

=== api-evangelist/conductor/examples/conductor-conductor-workflow-summary-example.json
{
  "workflowId": "500123",
  "workflowType": "example_value",
  "version": 10,
  "correlationId": "500123",
  "startTime": "example_value",
  "updateTime": "example_value",
  "endTime": "example_value",
  "status": "example_value",
  "input": "example_value",
  "output": "example_value",
  "reasonForIncompletion": "example_value",
  "executionTime": 10,
  "event": "example_value",
  "failedReferenceTaskNames": "example_value",
  "priority": 10
}
