=== api-evangelist/conductor/json-schema/conductor-conductor-task-summary-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "TaskSummary",
  "type": "object",
  "properties": {
    "taskId": {
      "type": "string"
    },
    "taskType": {
      "type": "string"
    },
    "taskDefName": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "workflowId": {
      "type": "string"
    },
    "workflowType": {
      "type": "string"
    },
    "correlationId": {
      "type": "string"
    },
    "scheduledTime": {
      "type": "string"
    },
    "startTime": {
      "type": "string"
    },
    "updateTime": {
      "type": "string"
    },
    "endTime": {
      "type": "string"
    },
    "input": {
      "type": "string"
    },
    "output": {
      "type": "string"
    },
    "reasonForIncompletion": {
      "type": "string"
    },
    "queueWaitTime": {
      "type": "integer"
    },
    "domain": {
      "type": "string"
    }
  }
}

=== api-evangelist/conductor/examples/conductor-conductor-task-summary-example.json
{
  "taskId": "500123",
  "taskType": "example_value",
  "taskDefName": "example_value",
  "status": "example_value",
  "workflowId": "500123",
  "workflowType": "example_value",
  "correlationId": "500123",
  "scheduledTime": "example_value",
  "startTime": "example_value",
  "updateTime": "example_value",
  "endTime": "example_value",
  "input": "example_value",
  "output": "example_value",
  "reasonForIncompletion": "example_value",
  "queueWaitTime": 10,
  "domain": "example_value"
}
